### ISSUE TITLE
Claws-Mail 4.0.0 and GnuPG

### ISSUE THREAD

**Issue by bayonne** [flathub/org.claws_mail.Claws-Mail#26]
Hello,

On my Ubuntu 20.04, trying to read encrypted emails fails with pinentry errors when the recipient's GPG key is not already in the host gpg-agent. Can this be reproduced by anyone else ?
The app is started with `--filesystem=xdg-run/gnupg:ro`.

**Comment by cobratbq** [comment]
Hi, thanks for letting me know.
- Please check if behavior is the same if such a gpg action is performed on host.
- IIUC you have error/warning messages. Please add those if possible. It helps to compare circumstances.
- About `--filesystem=xdg-run/gnupg:ro`: this is correct. You only need access to the existing socket already provided by `gpg-agent` on the host.

**Comment by bayonne** [comment]
Hello,

- gpg (version 2.2.19) on the command-line does not give me trouble. A graphical dialog lets me enter the passphrase to decrypt messages, if the key is not in gpg-agent (and if the passphrase is not stored in gnome-keyring).
- Claws-Mail shows this message "Couldn't decrypt: pinentry error" (above the message headers).

**Comment by cobratbq** [comment]
Initial research suggests that the flatpak package needs access to the session-bus to access gnupg/pinentry components. You can try running with `--talk-name=org.freedesktop.secrets`. (Full command to run: `flatpak run --talk-name=org.freedesktop.secrets org.claws_mail.Claws-Mail`) I have not tested this yet.

**Comment by bayonne** [comment]
I tried again with this session-bus permission; I still get the pinentry error on message decryption.

**Comment by cobratbq** [comment]
I can confirm. I'm still looking into the _right way_ to solve this. If this is a blocking issue for you, flatpak allows you to downgrade to an earlier commit, to Claws-Mail 3.18.

**Comment by cobratbq** [comment]
@bayonne please check the [new test build](https://github.com/flathub/org.claws_mail.Claws-Mail/pull/25#issuecomment-988245381). If the problem persists, which may be the case, make sure that `gpg-agent` is running before starting Claws-Mail.

If you run Claws-Mail from the console like `flatpak run org.claws_mail.Claws-Mail`, the first lines will report on a check to see if `gpg-agent` is accessible from within the package.

So far, I can confirm that Debian works out-of-the-box, and Fedora requires starting the gpg-agent manually beforehand.

**Comment by bayonne** [comment]
I tried this new test build on Ubuntu 20.04
When Claws-Mail is run from the console, there is a message about gpg-agent being available. But I still get the same errors as earlier.

**Comment by cobratbq** [comment]
Great! Although, in that case I do not have a solution yet. This is probably the case where gpg-agent is run as a systemd unit. I will see if I can check on an Ubuntu 20.04 set-up myself. This gives me a good lead. I suspect the same situation exists with Manjaro installs.

**Comment by bayonne** [comment]
@cobratbq gpg-agent is managed by systemd indeed.

**Comment by cobratbq** [comment]
@bayonne I can't debug this issue. I have a cleanly installed, updated Ubuntu 20.04 install. It just works. I can think of a few things, due to the way gpg-agent is managed:

1. use `pinentry-program` config option of `gpg-agent` to explicitly set the desired GUI program, e.g. `/usr/bin/pinentry-...` (`...` should be replaced by one of available variants. Depends per distro.)
1. restart `gpg-agent` for current user (if running as services, instead of activated upon socket connection) while logged into as this user. To give it a chance to adapt to user's current session. (This is educated guessing, but I give it only a small chance of succes.)
1. check if claws-mail is configured to make use of `gpg-agent` in gpg plugin settings. (Possibly explicitly setting path to `gpg`: `/usr/bin/gpg`.)
1. Stop systemd `gpg-agent` services and sockets. Start `gpg-agent` manually. Then test again to see if issue disappears in Claws-Mail flatpak. If so, that means we know the direction of the solution, at least.

**Comment by bayonne** [comment]
@cobratbq Plugin preferences in Claws-Mail look ok (including path to /usr/bin/gpg). Also added path to pinentry-gnome3 in `gpg-agent.conf`.
I tried  to start gpg-agent manually after stopping the service and sockets, with
`gpg-agent --daemon --verbose flatpak run ... ` (single line), but pinentry errors are still there.

These messages are repeated:

> gpg-agent[280958]: starting a new PIN Entry
> gpg-agent[280958]: failed to unprotect the secret key: pinentry error
> gpg-agent[280958]: failed to read the secret key
> gpg-agent[280958]: command 'PKDECRYPT' failed: pinentry error <Pinentry>
> gpg-agent[280958]: command 'PKDECRYPT' failed: No secret key
> 
and this appears too:
> gpg-agent[280958]: no running SCdaemon - starting it
> gpg-agent[280958]: can't connect to the SCdaemon: IPC connect call failed

**Comment by cobratbq** [comment]
> @cobratbq Plugin preferences in Claws-Mail look ok (including path to /usr/bin/gpg). Also added path to pinentry-gnome3 in `gpg-agent.conf`. I tried to start gpg-agent manually after stopping the service and sockets, with `gpg-agent --daemon --verbose flatpak run ... ` (single line), but pinentry errors are still there.
> 
> These messages are repeated:
> 
> > gpg-agent[280958]: starting a new PIN Entry
> > gpg-agent[280958]: failed to unprotect the secret key: pinentry error
> > gpg-agent[280958]: failed to read the secret key
> > gpg-agent[280958]: command 'PKDECRYPT' failed: pinentry error 
> > gpg-agent[280958]: command 'PKDECRYPT' failed: No secret key

The core issue here is the pinentry error. Because of this error, the follow-up steps fail due to missing the password.

> and this appears too:
> 
> > gpg-agent[280958]: no running SCdaemon - starting it
> > gpg-agent[280958]: can't connect to the SCdaemon: IPC connect call failed

The scdaemon, too, should be run on the host. If you do, it too will produce a socket. I have seen it exist as a socket, but that may not be as common.

**Comment by cobratbq** [comment]
For the SCdaemon issue: this is easily fixed by opening the socket.
At run-time: `flatpak run --socket=pcsc org.claws_mail.Claws-Mail` (and will be adjusted in next package)

**Comment by bayonne** [comment]
Thanks. (I do not have smart cards, though; `scdaemon` is not installed).

So something might be broken on my system, causing the pinentry errors.

**Comment by cobratbq** [comment]
I have just pushed some packaging changes. This will restore `pinentry` and `pcsc`. This may solve your issues.

**Comment by bayonne** [comment]
Thanks for the notice. Unfortunately I still get error messages like
``command 'PKDECRYPT' failed: pinentry error <Pinentry>``.

**Comment by cobratbq** [comment]
Thanks for letting me know. In that case, I will prepare the fully original solution for you in a test branch. I'll follow up soon.

**Comment by cobratbq** [comment]
@bayonne can you try [this test-build](https://github.com/flathub/org.claws_mail.Claws-Mail/pull/27#issuecomment-1037301144)? If you start it from the command-line, I would be curious about the output on stdout when Claws-Mail is just started. If this works, I would expect to see that `gpg-agent` is being started, i.e. not yet running.

This should be the same solution as I used first. From what I understand from your story, this should work.

**Comment by bayonne** [comment]
Hello,

With Commit: 7904e337debdb7d9f19bf835bcdf8927d4d06c24a9f67171e7bea44cd7ee0dae, I have:

> $ flatpak run --user org.claws_mail.Claws-Mail 
> INFO: gpg-agent is available.
> INFO: the socket to scdaemon on the host cannot be found. Claws-Mail will try to start it and connect to pcscd if needed.
> gpg-agent: a gpg-agent is already running - not starting a new one
> Starting Claws-Mail ...
> 
and messages cannot be decrypted because of pinentry errors.

**Comment by cobratbq** [comment]
I finally managed to reproduce in Ubuntu 22.04. The main problem is that the flatpak application runs on `DISPLAY=:99.0`, and that's how it is isolated. When the host `gpg-agent` process is called with request to display on `:99.0`, but that display is not available.

**Comment by echakr** [comment]
is there any work around for this, I tried to add 

`display :0`

in ~/.gnupg/gpgagent.conf, but this did not seem to fix it

**Comment by scabala** [comment]
I think adding a `--keep-display` to `gpg-agent` configuration should help then? From man page:
```man
Ignore requests to change the current tty or X window system's DISPLAY variable respectively.  This is useful to lock the pinentry to pop up at the tty or display you started the agent.
```

so from the surface it looks exactly like what is needed - make `gpg-agent` spawn `pinentry` on the display that `gpg-agent` is started with.

**Comment by cobratbq** [comment]
I can check. The situation is made complicated because there are some 3+ variations of set-ups with different characteristics and obstacles, including running GPG on host or flatpak-guest.

I am somewhat doubtful it makes a difference. If systemd starts gpg-agent without a display, it is doubtful a display is known at execution time. Furthermore, I have my concerns that tweaking a systemd-based run-configuration will be the right target in the chain of components.

**Comment by cobratbq** [comment]
I am closing this. The situation of distributions has changed over the years, and likely requires reinvestigating whether this is still a problem.

The current set-up of flatpak-package is such that flatpak attempts to make `gpg-agent` host sockets available for use. If not, pinentry is available inside the flatpak-package. This is possibly even superfluous. For now, I'll leave the situation as-is, until another report shows up such that there is a concrete situation to work off of.
